# Generated by Django 4.1.7 on 2023-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
