# Generated by Django 4.1.7 on 2023-03-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0005_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
